# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1417, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(590, 20, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color: rgb(228, 100, 104);")
        self.Title.setObjectName("Title")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 560, 1411, 20))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btn_check = QtWidgets.QPushButton(self.centralwidget)
        self.btn_check.setGeometry(QtCore.QRect(240, 620, 113, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_check.setFont(font)
        self.btn_check.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_check.setObjectName("btn_check")
        self.lineEdit_result = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_result.setGeometry(QtCore.QRect(510, 630, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_result.setFont(font)
        self.lineEdit_result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_result.setStyleSheet("background-color: rgb(155, 242, 145);")
        self.lineEdit_result.setText("")
        self.lineEdit_result.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_result.setReadOnly(True)
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.Title_2.setGeometry(QtCore.QRect(660, 590, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Title_2.setFont(font)
        self.Title_2.setObjectName("Title_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 160, 151, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 171, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 220, 151, 61))
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 140, 1411, 20))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 210, 1411, 20))
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(-10, 280, 1421, 20))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 300, 221, 41))
        self.label_4.setObjectName("label_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(-10, 350, 1421, 20))
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 370, 131, 41))
        self.label_5.setObjectName("label_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 420, 1411, 20))
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(470, 70, 20, 501))
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(980, 70, 20, 501))
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(0, 490, 1411, 20))
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(940, 440, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gender = QtWidgets.QComboBox(self.centralwidget)
        self.gender.setGeometry(QtCore.QRect(290, 90, 121, 41))
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.car = QtWidgets.QComboBox(self.centralwidget)
        self.car.setGeometry(QtCore.QRect(290, 160, 121, 41))
        self.car.setObjectName("car")
        self.car.addItem("")
        self.car.addItem("")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 440, 241, 41))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(560, 90, 141, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(590, 170, 91, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(550, 240, 171, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(540, 310, 201, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(580, 380, 131, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(600, 450, 61, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1070, 170, 81, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1030, 90, 161, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1070, 380, 91, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(1050, 250, 121, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(1090, 310, 41, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(1080, 450, 81, 21))
        self.label_22.setObjectName("label_22")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(1350, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.property = QtWidgets.QComboBox(self.centralwidget)
        self.property.setGeometry(QtCore.QRect(290, 230, 121, 41))
        self.property.setObjectName("property")
        self.property.addItem("")
        self.property.addItem("")
        self.workphone = QtWidgets.QComboBox(self.centralwidget)
        self.workphone.setGeometry(QtCore.QRect(290, 300, 121, 41))
        self.workphone.setObjectName("workphone")
        self.workphone.addItem("")
        self.workphone.addItem("")
        self.phone = QtWidgets.QComboBox(self.centralwidget)
        self.phone.setGeometry(QtCore.QRect(290, 370, 121, 41))
        self.phone.setObjectName("phone")
        self.phone.addItem("")
        self.phone.addItem("")
        self.work_phone = QtWidgets.QComboBox(self.centralwidget)
        self.work_phone.setGeometry(QtCore.QRect(290, 440, 121, 41))
        self.work_phone.setObjectName("work_phone")
        self.work_phone.addItem("")
        self.work_phone.addItem("")
        self.unemployee = QtWidgets.QComboBox(self.centralwidget)
        self.unemployee.setGeometry(QtCore.QRect(780, 90, 121, 41))
        self.unemployee.setObjectName("unemployee")
        self.unemployee.addItem("")
        self.unemployee.addItem("")
        self.work_type = QtWidgets.QComboBox(self.centralwidget)
        self.work_type.setGeometry(QtCore.QRect(1220, 440, 121, 41))
        self.work_type.setObjectName("work_type")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.work_type.addItem("")
        self.house_type = QtWidgets.QComboBox(self.centralwidget)
        self.house_type.setGeometry(QtCore.QRect(1220, 370, 121, 41))
        self.house_type.setObjectName("house_type")
        self.house_type.addItem("")
        self.house_type.addItem("")
        self.house_type.addItem("")
        self.house_type.addItem("")
        self.house_type.addItem("")
        self.house_type.addItem("")
        self.famil_status = QtWidgets.QComboBox(self.centralwidget)
        self.famil_status.setGeometry(QtCore.QRect(1220, 300, 121, 41))
        self.famil_status.setObjectName("famil_status")
        self.famil_status.addItem("")
        self.famil_status.addItem("")
        self.famil_status.addItem("")
        self.famil_status.addItem("")
        self.famil_status.addItem("")
        self.type_education = QtWidgets.QComboBox(self.centralwidget)
        self.type_education.setGeometry(QtCore.QRect(1220, 240, 121, 41))
        self.type_education.setObjectName("type_education")
        self.type_education.addItem("")
        self.type_education.addItem("")
        self.type_education.addItem("")
        self.type_education.addItem("")
        self.type_education.addItem("")
        self.type_income = QtWidgets.QComboBox(self.centralwidget)
        self.type_income.setGeometry(QtCore.QRect(1220, 160, 121, 41))
        self.type_income.setObjectName("type_income")
        self.type_income.addItem("")
        self.type_income.addItem("")
        self.type_income.addItem("")
        self.type_income.addItem("")
        self.type_income.addItem("")
        self.year_work = QtWidgets.QTextEdit(self.centralwidget)
        self.year_work.setGeometry(QtCore.QRect(1210, 90, 131, 31))
        self.year_work.setObjectName("year_work")
        self.number_childrens = QtWidgets.QTextEdit(self.centralwidget)
        self.number_childrens.setGeometry(QtCore.QRect(780, 170, 131, 31))
        self.number_childrens.setObjectName("number_childrens")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(920, 370, 71, 41))
        self.label_6.setObjectName("label_6")
        self.number_family = QtWidgets.QTextEdit(self.centralwidget)
        self.number_family.setGeometry(QtCore.QRect(780, 240, 131, 31))
        self.number_family.setObjectName("number_family")
        self.number_card = QtWidgets.QTextEdit(self.centralwidget)
        self.number_card.setGeometry(QtCore.QRect(780, 310, 131, 31))
        self.number_card.setObjectName("number_card")
        self.total_income = QtWidgets.QTextEdit(self.centralwidget)
        self.total_income.setGeometry(QtCore.QRect(780, 380, 131, 31))
        self.total_income.setObjectName("total_income")
        self.yearsold = QtWidgets.QTextEdit(self.centralwidget)
        self.yearsold.setGeometry(QtCore.QRect(780, 450, 131, 31))
        self.yearsold.setObjectName("yearsold")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Уровень риска заемщиков кредита"))
        self.btn_check.setText(_translate("MainWindow", "Проверить"))
        self.Title_2.setText(_translate("MainWindow", "Результат:"))
        self.label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">У клиента автомобиль?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">     (1 = да, 0 = нет)</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:14pt; color:#000000;\">                  Пол:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\',\'serif\'; font-size:14pt; color:#000000;\">(1 = мужской; 0 = женский)</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">У клиента собственная</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">      недвижимость?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">      (1 = да, 0 = нет)</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">У клиента рабочий телефон?<br />         (1 = да, 0 = нет)</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">У клиента телефон?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    (1 = да, 0 = нет)</p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "Лет"))
        self.gender.setItemText(0, _translate("MainWindow", "0"))
        self.gender.setItemText(1, _translate("MainWindow", "1"))
        self.car.setItemText(0, _translate("MainWindow", "0"))
        self.car.setItemText(1, _translate("MainWindow", "1"))
        self.label_10.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">У клиента адрес электронной почты?<br />                    (1 = да, 0 = нет)</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Клиент безработный?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    (1 = да, 0 = нет)</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Число детей:</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Количество членов семьи:</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Количество кредитной картой:</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Общая дохода:</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Возраст:</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Тип дохода:</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Количество лет работы:</p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Тип корпуса:</p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Тип образования:</p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Брак:</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Тип работа:</p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "Лет"))
        self.property.setItemText(0, _translate("MainWindow", "0"))
        self.property.setItemText(1, _translate("MainWindow", "1"))
        self.workphone.setItemText(0, _translate("MainWindow", "0"))
        self.workphone.setItemText(1, _translate("MainWindow", "1"))
        self.phone.setItemText(0, _translate("MainWindow", "0"))
        self.phone.setItemText(1, _translate("MainWindow", "1"))
        self.work_phone.setItemText(0, _translate("MainWindow", "0"))
        self.work_phone.setItemText(1, _translate("MainWindow", "1"))
        self.unemployee.setItemText(0, _translate("MainWindow", "0"))
        self.unemployee.setItemText(1, _translate("MainWindow", "1"))
        self.work_type.setItemText(0, _translate("MainWindow", "Laborers"))
        self.work_type.setItemText(1, _translate("MainWindow", "Sales staff"))
        self.work_type.setItemText(2, _translate("MainWindow", "Core staff"))
        self.work_type.setItemText(3, _translate("MainWindow", "Managers"))
        self.work_type.setItemText(4, _translate("MainWindow", "Drivers"))
        self.work_type.setItemText(5, _translate("MainWindow", "High skill tech staff"))
        self.work_type.setItemText(6, _translate("MainWindow", "Accountants"))
        self.work_type.setItemText(7, _translate("MainWindow", "Medicine staff"))
        self.work_type.setItemText(8, _translate("MainWindow", "Cooking staff"))
        self.work_type.setItemText(9, _translate("MainWindow", "Security staff"))
        self.work_type.setItemText(10, _translate("MainWindow", "Cleaning staff"))
        self.work_type.setItemText(11, _translate("MainWindow", "Private service staff"))
        self.work_type.setItemText(12, _translate("MainWindow", "Low-skill Laborers"))
        self.work_type.setItemText(13, _translate("MainWindow", "Secretaries"))
        self.work_type.setItemText(14, _translate("MainWindow", "Waiters/barmen staff"))
        self.work_type.setItemText(15, _translate("MainWindow", "HR staff"))
        self.work_type.setItemText(16, _translate("MainWindow", "IT staff"))
        self.work_type.setItemText(17, _translate("MainWindow", "Realty agents"))
        self.work_type.setItemText(18, _translate("MainWindow", "Other"))
        self.house_type.setItemText(0, _translate("MainWindow", "House / apartment"))
        self.house_type.setItemText(1, _translate("MainWindow", "With parents"))
        self.house_type.setItemText(2, _translate("MainWindow", "Municipal apartment"))
        self.house_type.setItemText(3, _translate("MainWindow", "Rented apartment"))
        self.house_type.setItemText(4, _translate("MainWindow", "Office apartment"))
        self.house_type.setItemText(5, _translate("MainWindow", "Co-op apartment"))
        self.famil_status.setItemText(0, _translate("MainWindow", "Married"))
        self.famil_status.setItemText(1, _translate("MainWindow", "Single / not married"))
        self.famil_status.setItemText(2, _translate("MainWindow", "Civil marriage"))
        self.famil_status.setItemText(3, _translate("MainWindow", "Separated"))
        self.famil_status.setItemText(4, _translate("MainWindow", "Widow"))
        self.type_education.setItemText(0, _translate("MainWindow", "Secondary / secondary special"))
        self.type_education.setItemText(1, _translate("MainWindow", "Higher education"))
        self.type_education.setItemText(2, _translate("MainWindow", "Incomplete higher"))
        self.type_education.setItemText(3, _translate("MainWindow", "Lower secondary"))
        self.type_education.setItemText(4, _translate("MainWindow", "Academic degree"))
        self.type_income.setItemText(0, _translate("MainWindow", "Working"))
        self.type_income.setItemText(1, _translate("MainWindow", "Commercial associate"))
        self.type_income.setItemText(2, _translate("MainWindow", "Pensioner"))
        self.type_income.setItemText(3, _translate("MainWindow", "State servant"))
        self.type_income.setItemText(4, _translate("MainWindow", "Student"))
        self.label_6.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Китайский</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    юань</p></body></html>"))
